src/jiranCommsProject/helloboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^(?P<viewer_id>\d+)/$', 'helloboard.views.board_list', name='board_list'), # viewer_id
    url(r'^(?P<viewer_id>\d+)/(?P<id>\d+)/$', 'helloboard.views.board_detail', name='board_detail'), # viewer_id, board_id
    url(r'^(?P<viewer_id>\d+)/(?P<id>\d+)/edit/$', 'helloboard.views.board_update', name='board_update'), # viewer_id, board_id
    url(r'^(?P<viewer_id>\d+)/(?P<id>\d+)/delete/$', 'helloboard.views.board_delete', name='board_delete'), # viewer_id, board_id
    url(r'^(?P<viewer_id>\d+)/board_create/$', 'helloboard.views.board_create', name='board_create'),
]

src/jiranCommsProject/helloboardRestApi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^helloboard/board_next/$', 'helloboardRestApi.views.board_next', name='rest_board_next'), # viewer_id
]

src/jiranCommsProject/jiranCommsProject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from helloboard.models import Board

# # ViewSets define the view behavior.
# class BoardViewSet(viewsets.ModelViewSet):
#     queryset = Board.objects.all()
#     serializer_class = BoardSerializer

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'boards', BoardViewSet)

urlpatterns = [
    url(r'^restapi/', include('helloboardRestApi.urls', namespace='restapi')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^helloboard/', include('helloboard.urls', namespace='helloboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/jiranCommsProject/helloboard/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.models import User


class UserProfile(models.Model):
	user = models.OneToOneField(User)
	nickname = models.CharField(max_length=128)
	subscribe_boards = models.ManyToManyField('Viewer', related_name='subscribe_set', blank=True, null=True)
	
	def __str__(self):
		return self.nickname

class Viewer(models.Model):
	device_id = models.CharField(max_length=100)
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

def upload_location(instance, filename):
	# id 가 생성되기 전의 시점이기 때문에 id를 이름에 사용해서는 안되겠다.
	return "%s_%s_%s" %(instance.author, instance.id, filename)

class Board(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	title = models.CharField(max_length=30)
	content = models.TextField()
	image = models.ImageField(
		upload_to=upload_location,
		blank=True, 
		null=True, 
		width_field="width_field", 
		height_field="height_field")
	width_field = models.IntegerField(default=0)
	height_field = models.IntegerField(default=0)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	author = models.CharField(max_length=30)
	target = models.ForeignKey('Viewer',
			related_name="targets",
			related_query_name="target"
		)

	def __str__(self):
		return self.title

	def get_absolute_url(self, viewer_id):
		return reverse("helloboard:board_list", kwargs={'viewer_id': viewer_id})

	# class Meta:
	# 	ordering = ["created"]

class Reply(models.Model):
	content = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	author = models.CharField(max_length=30) 
	board_id = models.ForeignKey(
			'Board',
		)

	def __str__(self):
		return self.content

src/jiranCommsProject/helloboardRestApi/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

# Create your models here.
class Test(models.Model):
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

src/jiranCommsProject/helloboard/forms.py
from django import forms

from .models import Board

class BoardForm(forms.ModelForm):
	class Meta:
		model = Board
		fields = [
			"title",
			"content",
			"target",
			"image",
		]

src/jiranCommsProject/helloboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Board, Viewer
from .forms import BoardForm
import logging
from django.contrib.auth.models import User

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



logger = logging.getLogger("views")

def board_list(request, viewer_id):
	print("[DEBUG]: viewer_id = " + str(viewer_id))
	queryset_list = Board.objects.filter(target__id=viewer_id).order_by('-created')
	
	viewer_list = Viewer.objects.all()
	logger.debug(viewer_list)
	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page

	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
		"target": queryset_list.first().target,
		"object_list": queryset,
		"viewer_list": viewer_list
	}
	return render(request, "helloboard/board_list.html", context)


def board_detail(request, viewer_id, id=None):
	instance = get_object_or_404(Board, id=id)
	context = {
		"title": instance.title,
		"instance": instance,
	}
	return render(request, "helloboard/board_detail.html", context)

def board_create(request, viewer_id=None):
	if request.user.is_active:
		viewer = Viewer.objects.get(id=viewer_id)
		print("viewer_id = " + str(viewer.id))
		form = BoardForm(request.POST or None, request.FILES or None, initial={'target': viewer})
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			return HttpResponseRedirect(instance.get_absolute_url(viewer_id))
			
		context = {
			"is_update": False,
			"form": form,
		}
		return render(request, "helloboard/board_form.html", context)
	else:
		return HttpResponseRedirect("accounts/registraion")

def board_update(request, viewer_id, id=None):
	instance = get_object_or_404(Board, id=id)
	form = BoardForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"is_update": True,
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "helloboard/board_form.html", context)

def board_delete(request, viewer_id, id=None):
	instance = get_object_or_404(Board, id=id)
	instance.delete()
	return redirect("helloboard:board_list")

src/jiranCommsProject/helloboardRestApi/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from helloboard.models import Board
from .serializers import BoardSerializer

@csrf_exempt
def board_next(request):
	if request.method == 'POST':
		target_id = request.POST.get('target_id')
		board_id = request.POST.get('board_id')

		next_obj = Board.objects.filter(target__id=target_id).filter(id__gt=board_id)
		
		if next_obj:
			serializer = BoardSerializer(next_obj.first())
			return JSONResponse(serializer.data)
	
		first_obj = Board.objects.filter(target__id=target_id)[0]
		serializer = BoardSerializer(first_obj)
		return JSONResponse(serializer.data)


class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)

src/jiranCommsProject/helloboard/templates/base.html
<!--DOCTYPE html -->

<!DOCTYPE html>
<html>
<head>
	<title>{% block head_title %}Hello board!{% endblock head_title %}</title>

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class='container'>
	<ul class="nav navbar-nav navbar-right">
		{% if user.is_authenticated %}
			<li><a href="{% url 'auth_logout' %}">Logout</a></li>
		{% else %}
			<li><a href="{% url 'auth_login' %}">Login</a></li>
			<li><a href="{% url 'registration_register' %}">Register</a></li>
		{% endif %}
	</ul>

	<div class="jumbotron" align="center">
	    <h1>Hello board!</h1> 
	    <p>
	    {% if user.is_authenticated %}
	      {{ user.username }} 님!
	    {% endif %}
	    보여주고 싶은 얘기들을 마음껏 적으세요!
	    </p> 
	    
	</div>    


	{% block content %}
		
	{% endblock content %}
</div>


</body>
</html>

src/jiranCommsProject/helloboard/templates/helloboard/board_detail.html
<!--DOCTYPE html -->
{% extends "base.html" %}

{% block head_title %}
{{ insatance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
<h1>{{ title }} <small>{{ instance.created }}</small></h1>
<div>
	{% if instance.image %}  
	<img src='{{ instance.image.url }}' class='img-responsive'/>
	{% endif %}  
<!-- {{ instance.id }}<br/> -->
<!-- {{ instance.title }}<br/> -->
{{ instance.content|linebreaks }}<br/>
{{ instance.created }}<br/>
{{ instance.updated }}<br/>
</div>

{% endblock content %}
</body>
</html>

src/jiranCommsProject/helloboard/templates/helloboard/board_form.html
<!--DOCTYPE html -->
{% extends "base.html" %}
{% block head_title %}
{{ title }} | {{ block.super }}
{% endblock head_title %}


	
{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
	{{ form.as_p }}	
	<input type="submit" value="작성완료"/>
</form>
{% endblock content %}

src/jiranCommsProject/helloboard/templates/helloboard/board_list.html
<!--DOCTYPE html -->
{% extends "base.html" %}

{% block head_title %}
{{ insatance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}



<h1 class='text-primary text-center'>{{ target.name }}<small>에 보여지고 있습니다</small><br></h1>
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">타겟 선택
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    {% for viewer in viewer_list %}
      <li><a href="{% url 'helloboard:board_list' viewer_id=viewer.id %}"/>{{ viewer.name }} </li>
    {% endfor %}
  </ul>
  <a href="{% url 'helloboard:board_create' viewer_id=target.id %}" class="btn btn-primary" role="button">작성하기</a>
</div>

<div align="right">
  <div class="pagination">
      <span class="step-links">
          {% if object_list.has_previous %}
              <a href="?page={{ object_list.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
          </span>

          {% if object_list.has_next %}
              <a href="?page={{ object_list.next_page_number }}">next</a>
          {% endif %}
      </span>
  </div>
</div>
{% for obj in object_list %}
<div class="row">
  <div>
    <div class="thumbnail">
      
      <div class="caption">
        <h3 class='text-information'>{{ obj.title }}<br/></h3>
        {% if obj.image %}  
        <img src='{{ obj.image.url }}' class='img-responsive'/>
        {% endif %}
        <p>{{ obj.content|linebreaks|truncatechars:100 }}<br/></p>
        <p class='text-success'>{{ obj.created|timesince }} ago<br/></p>
        <p>
        <a href="{%url "helloboard:board_detail" viewer_id=target.id id=obj.id %}" class="btn btn-primary" role="button">View</a>

        <!-- 만약 작성자라면 edit 버튼을 보여준다 -->
        {% if obj.user.id == user.id %}
          <a href="{%url "helloboard:board_update" viewer_id=target.id id=obj.id %}" class="btn btn-primary" role="button">Edit</a>
        {% endif %}
        </p>
      </div>
    </div>
  </div>
</div>

{% endfor %}

<div align="right">
  <div class="pagination">
      <span class="step-links">
          {% if object_list.has_previous %}
              <a href="?page={{ object_list.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
          </span>

          {% if object_list.has_next %}
              <a href="?page={{ object_list.next_page_number }}">next</a>
          {% endif %}
      </span>
  </div>
</div>
{% endblock content %}
</html>